apiVersion: v1
kind: Namespace
metadata:
  name: petstore
  labels:
    name: petstore
    app.kubernetes.io/name: petstore
    app.kubernetes.io/instance: petstore
    app.kubernetes.io/component: namespace