apiVersion: v1
kind: ServiceAccount
metadata:
  name: petstore
  namespace: petstore
  labels:
    app.kubernetes.io/name: petstore
    app.kubernetes.io/instance: petstore
    app.kubernetes.io/component: serviceaccount
  annotations:
    iam.gke.io/gcp-service-account: petstore@tesserix-platform.iam.gserviceaccount.com
automountServiceAccountToken: false